# Site settings
title: Carson Lourenco
description: Carson Lourenco Software Engineer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Carson Lourenco
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Engineer
email: carson.lourenco@gmail.com
twitter_username: lorem_ipsum
github_username:  bladesaunterer
gplus_username:  lorem_ipsum
linkedin_username: carson-lourenco

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
